import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"],
  weight: ['200','300', '400','500','600', '700','800','900'],
  variable: '--font-nunitoSans',
 });

export const metadata = {
  title: "wildbites",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
